config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :body, presence: true, length: {minimum: 50}
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true, length: {minimum: 40}
  validates :description, presence: true, length: {minimum: 150}

  has_many :answers
end

app/controllers/answers_controller.rb
require 'pry'

class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)

    if @answer.save
      flash[:notice] = 'Answer added.'
      redirect_to question_path(@question)
    else
      @question = Question.find(params[:question_id])
      flash[:notice] = 'failure'
      render 'questions/show'
    end
  end

  private
  def answer_params
    params.require(:answer).permit(:body).merge(question_id: params[:question_id])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order('created_at DESC')
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = 'Question added.'
      redirect_to '/'
    else
      render :new
    end
  end
  private
  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |a| %>
  <%= a.label :body %>
  <%= a.text_field :body %>
  <%= a.submit "Add answer." %>
<%- end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<div class="large-12">

  <%= form_for @question do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.submit "Add question" %>
  <%- end -%>
</div>

app/views/questions/index.html.erb
<h1>Questions!</h1>
<p class="text-center">
<a class="button" data-dropdown="autoCloseExample" aria-controls="autoCloseExample" aria-expanded="false">Link Dropdown &raquo;</a>
<div class="circle">
  <ul id="autoCloseExample" class="f-dropdown" data-dropdown-content tabindex="-1" aria-hidden="true" aria-autoclose="false" tabindex="-1">
  <% @questions.each do | q | %>

        <li><%= link_to q.title, question_path(q) %></li>
  <% end %>
  </ul>
</div>
</p>

app/views/questions/new.html.erb
<h1> New Question </h1>
<%- if @question.errors.present? -%>
  <div class="large-12 alert-box alert" data-alert>
    <ul>
      <%- @question.errors.full_messages.each do |error| -%>
        <li><%= error %></li>
      <%- end -%>
    </ul>
  </div>
<%- end -%>

<%= render "form" %>
<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<h3><%= @question.description %></h3>
<p><%= flash[:notice] %></p>
<%- if @answer.errors.present? -%>
  <div class="large-12 alert-box alert" data-alert>
    <ul>
      <%- @answer.errors.full_messages.each do |error| -%>
        <li><%= error %></li>
      <%- end -%>
    </ul>
  </div>
<%- end -%>

<%= render "answers/form" %>

<% @question.answers.each do | a | %>
      <li><%= a.body %></li>
<% end %>

<p class="text-center">
<%= link_to 'Back.', '/questions' %>
</p>